/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef thriftConnection_CONSTANTS_H
#define thriftConnection_CONSTANTS_H

#include "thriftConnection_types.h"



class thriftConnectionConstants {
 public:
  thriftConnectionConstants();

};

extern const thriftConnectionConstants g_thriftConnection_constants;



#endif
